version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Using system Docker (already running)"
      - docker --version
      - python --version
      - pip install --upgrade pip pytest

  build:
    commands:
      - echo "Running tests"
      - pytest

  post_build:
    commands:
      - echo "Build completed"
