version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - python --version
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest

  build:
    commands:
      - echo "Running tests"
      - pytest

  post_build:
    commands:
      - echo "Build completed"
